# -*- coding: utf-8 -*-
"""Python-OOP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ick8Wl-hJt32Fumxy7tg3Jzjkdh2o8-
"""


class Item:
    def __init__(self, name: str, price: float, qty=0):
        # Run Validation to receive argument
        assert price >= 0, f"Price {price} is less than zero"
        assert qty >= 0, f"Quantity: {qty} is less than zero"

        # instance Attribute - self object
        self.name = name
        self.price = price
        self.qty = qty

    def total_price(self):
      return self.price * self.qty


pc = Item('Laptop', 45000, 5)
print(f'{pc.qty} pc Total Price {pc.total_price()}')

pc.__dict__

Item.__dict__

pc.price

pc.total_price()
